#!/usr/bin/env python3
"""Generate CLEAN, context-ready hero markdown for the magic_chess_gogo schema.

Design goal (per Kamil, 2026-06-28): the schema is ready-to-read context, not a data
dump. So NO internal ids in the prose (synergy r-ids, raw skill-id arrays, equip-slot
indices), NO codename/icon/nameSource, NO meta-counts. Clean names only.

Sources:
- Exact stats + clean synergy names: the LIVE S6 client export `dataset_live_s6.json`.
- Skill name/effect/scaling + recommended equipment: the in-game Hero-Details screenshots,
  transcribed into `screenshot_heroes.json` (keyed by hero id). Optional: any hero missing
  from it simply omits those lines (we never ship the unreliable parsed skill names).
"""
import json, collections, os

ROOT = "vape/entity/storage/magic-chess-gogo/game-client-from-friend/dataset_s6.json"
SHOTS = "work_dir/saori/mcgg/screenshot_heroes.json"   # optional, from the screenshot pass
OUT = "vape/entity/memory/schemata/magic_chess_gogo/concrete_things/heroes"
os.makedirs(OUT, exist_ok=True)

# The 20 synergy names, first-party confirmed 2026-06-28 (loc name-bands + FX_Fetter + m_Sort).
KNOWN = {1: "Bruiser", 2: "Dauntless", 3: "Defender", 4: "Weapon Master", 5: "Marksman",
         6: "Mage", 7: "Stargazer", 8: "Assassin", 9: "Scavenger", 10: "Phasewarper",
         50: "Emberlord", 51: "Exorcist", 52: "Heartbond", 53: "Astro Power", 54: "Dragoncaller",
         55: "Neobeasts", 56: "Kishin", 57: "Enchanted Tales", 58: "Mystic Meow",
         59: "Northern Vale"}

d = json.load(open(ROOT))
heroes = d["heroes"]
shots = json.load(open(SHOTS)) if os.path.exists(SHOTS) else {}

def syn_split(h):
    """Return (class_names, faction_names) as clean strings, no ids."""
    cls = [KNOWN.get(s, f"synergy {s}") for s in h.get("synergies", []) if s < 50]
    fac = [KNOWN.get(s, f"synergy {s}") for s in h.get("synergies", []) if s >= 50]
    return cls, fac

def star_table(stars):
    head = ("| Star | HP | PhyAtk | MagAtk | PhyDef | MagDef | AtkSpd | MoveSpd "
            "| Crit | DPS | EHP | MP |")
    sep = "|---|---|---|---|---|---|---|---|---|---|---|---|"
    rows = [head, sep]
    for st in stars:
        rows.append("| {star} | {hp} | {phyAtk} | {magAtk} | {phyDef} | {magDef} "
                    "| {atkSpeed} | {moveSpeed} | {crit} | {dps} | {ehp} | {mp} |".format(**st))
    return "\n".join(rows)

def hero_block(h):
    cls, fac = syn_split(h)
    cls_s = ", ".join(cls) or "none"
    fac_s = ", ".join(fac) or "none"
    role = "Front-row" if h.get("isTank") else "Back-row"
    lines = [f"### {h['name']}  (id {h['id']}, cost {h['cost']})", ""]
    lines.append(f"- **Class:** {cls_s}  ·  **Faction:** {fac_s}  ·  **Position:** {role}")
    sh = shots.get(str(h["id"])) or {}
    if sh.get("skill"):
        eff = sh.get("effect", "").strip()
        lines.append(f"- **Skill ({sh['skill']}):** {eff}")
        if sh.get("scaling"):
            lab = sh.get("scalingLabel", "Per star")
            lines.append(f"- **{lab} (1/2/3 star):** {' / '.join(sh['scaling'])}")
    if sh.get("equipment"):
        lines.append(f"- **Recommended equipment:** {' · '.join(sh['equipment'])}")
    lines += ["", star_table(h["stars"]), ""]
    return "\n".join(lines)

HEADER = (
    "<!-- GENERATED by work_dir/saori/mcgg/gen_heroes.py from the datamined S6 client export "
    "(dataset_s6.json, v302.1, matches the live v302.2 client) for stats + synergies, and "
    "screenshot_heroes.json for skills/equipment. Regenerate on a season patch; do not "
    "hand-edit. -->\n"
)

COST_NOTE = {
    1: "Cheapest tier: many copies in the shared pool, the early-game backbone.",
    2: "Low tier: still common, the bridge into mid-game synergy.",
    3: "Mid tier: the contested workhorses, common 3-star targets.",
    4: "High tier: strong carries, scarce in the pool.",
    5: "Top tier: the legendaries, rarest pulls, game-deciding when starred.",
}

specials = [h for h in heroes if h.get("isSummon") or not h.get("synergies")]
normal = [h for h in heroes if h not in specials]
by_cost = collections.defaultdict(list)
for h in normal:
    by_cost[h["cost"]].append(h)
for c in by_cost:
    by_cost[c].sort(key=lambda x: x["name"])

# --- cost files ---
for c in range(1, 6):
    hs = by_cost.get(c, [])
    body = [HEADER, f"# Cost {c} Heroes (MCGG S6)", ""]
    body.append(f"{COST_NOTE[c]}  {len(hs)} heroes at this cost.")
    body.append("")
    for h in hs:
        body.append(hero_block(h))
    open(f"{OUT}/cost_{c}.md", "w").write("\n".join(body).rstrip() + "\n")

# --- special units ---
body = [HEADER, "# Special / Non-Shop Units (MCGG S6)", ""]
body.append("Units outside the normal shop roster: summons and special entries. They are not "
            "bought from the shop and carry no synergies of their own.")
body.append("")
for h in specials:
    body.append(hero_block(h))
    if h["id"] == 179:
        body.append("> Summoned by the Dragoncaller faction; scales with that synergy's tier "
                    "(note: 4 star tiers, not 3).\n")
open(f"{OUT}/special_units.md", "w").write("\n".join(body).rstrip() + "\n")

# --- index ---
dist = {c: len(by_cost.get(c, [])) for c in range(1, 6)}
idx = [HEADER, "# Heroes (MCGG S6): the full roster, by cost tier", ""]
idx.append("The complete S6 roster. Per-cost files carry each hero's synergies, position, skill, "
           "recommended equipment, and full per-star stat table. This index is the map. Stats are "
           "exact from the live client; skills and equipment are from the in-game screenshots. "
           "Governed by ../disclaimer.md (regenerate on a season patch).")
idx.append("")
idx.append("## Cost distribution (shop heroes)")
idx.append("")
idx.append("| Cost | Heroes | Detail |")
idx.append("|---|---|---|")
for c in range(1, 6):
    idx.append(f"| {c} | {dist[c]} | [cost_{c}.md](cost_{c}.md) |")
idx.append(f"| special | {len(specials)} | [special_units.md](special_units.md) |")
total = sum(dist.values()) + len(specials)
idx.append(f"| **total** | **{total}** | |")
idx.append("")
idx.append("## Star-up")
idx.append("")
idx.append("Each hero has 3 star tiers (the Dragon summon has 4). Merge 3 copies to raise a star "
           "(1->2->3); nine 1-stars make a 3-star. HP roughly 1.8x per step, so a 3-star is a "
           "large power spike. Every per-star stat block lives in the cost files.")
idx.append("")
idx.append("## Roster at a glance  (name: class / faction)")
idx.append("")
for c in range(1, 6):
    parts = []
    for h in by_cost.get(c, []):
        cls, fac = syn_split(h)
        parts.append(f"{h['name']} ({', '.join(cls) or '-'} / {', '.join(fac) or '-'})")
    idx.append(f"**Cost {c}:** " + " · ".join(parts))
    idx.append("")
idx.append("**Special:** " + " · ".join(h["name"] for h in specials))
idx.append("")
open(f"{OUT}/index.md", "w").write("\n".join(idx).rstrip() + "\n")

print("wrote:", sorted(os.listdir(OUT)))
print("normal:", len(normal), "specials:", len(specials), "total:", len(heroes))
print("dist:", dist, " skills-from-shots:", len(shots))
